####
# This Dockerfile is used in order to build a container that runs the Spring application in JVM mode
#
# Before building the container image run:
#
# mvn clean package
#
# Then, build the image with:
#
# docker build -f Dockerfile.jvm -t spring/spring-cqrs-poc-jvm .
#
# Then run the container using:
#
# docker run -i -d --name spring-cqrs-poc-jvm -p 8080:8080 spring/spring-cqrs-poc-jvm
#
###

# For Java 11, try this
FROM adoptopenjdk/openjdk11:alpine-jre

# Refer to Maven build -> finalName
ARG JAR_FILE=target/*.jar

# cd /opt/app
WORKDIR /opt/app

# cp target/spring-cqrs-poc-0.0.1-SNAPSHOT.jar /opt/app/app.jar
COPY ${JAR_FILE} app.jar

# java -jar /opt/app/app.jar
ENTRYPOINT ["java","-jar","app.jar"]